---
- name: Sample NETCONF config
  hosts: podiosv
  connection: local
  gather_facts: True
  vars_files:
    - var_files/passwords.yml
  tasks:

    - name: set ntp server via NETCONF
      netconf_config_kev:
        host: "{{inventory_hostname}}"
        username: "{{username}}"
        hostkey_verify: False
        password: "{{password}}"
        xml: |
            <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/ned/ios" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
                <ntp>
                    <server>
                      <server-list>
                        <ip-address>5.5.5.7</ip-address>
                      </server-list>
                    </server>
                </ntp>
              </native>
            </config>
