---
- name: Create config output directory
  file:
    path: "{{ config_output_directory }}"
    state: directory

- name: Generate ASR Configuration Files
  template:
    src: router_full.j2
    dest: "{{ config_output_directory }}/{{item.hostname}}.txt"
  with_items: '{{podiosv}}'
  run_once: true

# split these out so config will match device
- ios_template:
    host: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    src: "router_full.j2"
  with_items: '{{podiosv[0]}}'
  tags:
    - deploy
  when: inventory_hostname[-1] == "1"

- ios_template:
    host: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    src: "router_full.j2"
  with_items: '{{podiosv[1]}}'
  tags:
    - deploy
  when: inventory_hostname[-1] == "2"